version: '3.8'

services:
  pix-key:
    image: postgres:latest
    container_name: pix_key_db
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: pix_key_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 120740
    ports:
      - 5435:5432
    expose:
      - 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge